"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ui } from "@/lib/ui-classes";
import { Job } from "@/types/job";
import { CATEGORY_LABELS, ExpenseCategory, ExpenseClaim, ExpensePaymentMethod, PAYMENT_LABELS, STATUS_LABELS } from "@/types/expense";

const money = (n:number) => new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const statusClass=(s:ExpenseClaim["status"])=>s==="paid"?"text-success border-success/30 bg-success/10":s==="approved"?"text-accent border-accent/30 bg-accent/10":s==="rejected"?"text-danger border-danger/30 bg-danger/10":"text-warning border-warning/30 bg-warning/10";

export function ExpenseClaimsClient({ initialClaims, jobs }: { initialClaims: ExpenseClaim[]; jobs: Job[] }) {
  const router=useRouter();
  const [claims,setClaims]=useState(initialClaims);
  const [open,setOpen]=useState(false);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState("");
  const [category,setCategory]=useState<ExpenseCategory>("fuel");
  const [amount,setAmount]=useState("");
  const [date,setDate]=useState(new Date().toISOString().slice(0,10));
  const [description,setDescription]=useState("");
  const [vendor,setVendor]=useState("");
  const [projectId,setProjectId]=useState("");
  const [paymentMethod,setPaymentMethod]=useState<ExpensePaymentMethod|"">("");
  const [reference,setReference]=useState("");
  const [notes,setNotes]=useState("");
  const [receipt,setReceipt]=useState<File|null>(null);

  const totals=useMemo(()=>({pending:claims.filter(c=>c.status==="pending").reduce((s,c)=>s+c.amount,0),approved:claims.filter(c=>c.status==="approved"||c.status==="paid").reduce((s,c)=>s+c.amount,0)}),[claims]);

  async function refresh(){const r=await fetch("/api/expenses",{cache:"no-store"});const j=await r.json();if(r.ok&&j.success)setClaims(j.data.expenses);router.refresh();}
  async function submit(e:FormEvent){e.preventDefault();setError("");const numeric=Number(amount);if(!Number.isFinite(numeric)||numeric<=0){setError("Enter a valid amount.");return;}setBusy(true);try{const r=await fetch("/api/expenses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,amount:numeric,expenseDate:date,description:description.trim(),vendor:vendor.trim()||undefined,projectId:projectId||undefined,paymentMethod:paymentMethod||undefined,paymentReference:reference.trim()||undefined,notes:notes.trim()||undefined})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Could not submit claim");const claim:ExpenseClaim=j.data.expense;if(receipt){const f=new FormData();f.append("receipt",receipt);const u=await fetch(`/api/expenses/${claim._id}/receipt`,{method:"POST",body:f});if(!u.ok)throw new Error("Claim submitted, but receipt upload failed. You can upload it again from the claim list.");}setAmount("");setDescription("");setVendor("");setProjectId("");setReference("");setNotes("");setReceipt(null);setOpen(false);await refresh();}catch(err){setError(err instanceof Error?err.message:"Could not submit claim");}finally{setBusy(false);}}
  async function deleteClaim(c:ExpenseClaim){if(!confirm(`Delete ${c.expenseNumber}?`))return;setBusy(true);try{const r=await fetch(`/api/expenses/${c._id}`,{method:"DELETE"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Could not delete claim");await refresh();}catch(err){setError(err instanceof Error?err.message:"Could not delete claim");}finally{setBusy(false);}}
  async function upload(c:ExpenseClaim,file:File){setBusy(true);setError("");try{const f=new FormData();f.append("receipt",file);const r=await fetch(`/api/expenses/${c._id}/receipt`,{method:"POST",body:f});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Receipt upload failed");await refresh();}catch(err){setError(err instanceof Error?err.message:"Receipt upload failed");}finally{setBusy(false);}}

  return <div className="space-y-5">
    <div className="grid grid-cols-2 gap-3"><div className={`${ui.card} p-4`}><p className="text-xs text-ink-faint">Pending</p><p className="mt-1 text-xl font-semibold text-warning">{money(totals.pending)}</p></div><div className={`${ui.card} p-4`}><p className="text-xs text-ink-faint">Approved / Paid</p><p className="mt-1 text-xl font-semibold text-success">{money(totals.approved)}</p></div></div>
    {error?<div className={`${ui.card} border-danger/30 bg-danger/10 p-3 text-sm text-danger`}>{error}</div>:null}
    <button className={ui.btnAction} onClick={()=>setOpen(v=>!v)}>{open?"Close claim form":"+ Submit expense claim"}</button>
    {open?<form onSubmit={submit} className={`${ui.card} space-y-4 p-4`}><div className="grid grid-cols-2 gap-3"><label className={ui.label}>Category<select className={`${ui.input} mt-1`} value={category} onChange={e=>setCategory(e.target.value as ExpenseCategory)}>{Object.entries(CATEGORY_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className={ui.label}>Amount (₹)<input className={`${ui.input} mt-1`} type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label></div><label className={ui.label}>Date<input className={`${ui.input} mt-1`} type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label className={ui.label}>Description<input className={`${ui.input} mt-1`} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Fuel for site visit, parking, supplies…" required/></label><label className={ui.label}>Linked job<select className={`${ui.input} mt-1`} value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">General field expense</option>{jobs.map(j=><option key={j._id} value={j._id}>{j.customerName} · {j.address}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className={ui.label}>Vendor<input className={`${ui.input} mt-1`} value={vendor} onChange={e=>setVendor(e.target.value)} placeholder="Optional"/></label><label className={ui.label}>Paid via<select className={`${ui.input} mt-1`} value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as ExpensePaymentMethod|"")}><option value="">Not specified</option>{Object.entries(PAYMENT_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label className={ui.label}>Reference<input className={`${ui.input} mt-1`} value={reference} onChange={e=>setReference(e.target.value)} placeholder="UPI / receipt / transaction reference"/></label><label className={ui.label}>Notes<textarea className="mt-1 min-h-20 w-full rounded-lg border border-border-default bg-surface-2 p-3 text-sm text-ink outline-none focus:border-accent" value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className={ui.label}>Receipt image<input className="mt-1 block w-full text-sm text-ink-muted" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setReceipt(e.target.files?.[0]||null)}/></label><button disabled={busy} className={ui.btnAction}>{busy?"Submitting…":"Submit for approval"}</button></form>:null}
    <div><div className="mb-3 flex items-center justify-between"><h2 className="text-base font-semibold">My claims</h2><span className="text-xs text-ink-faint">{claims.length} total</span></div><div className="space-y-3">{claims.map(c=><div key={c._id} className={`${ui.card} p-4`}><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-accent">{c.expenseNumber}</p><p className="mt-1 font-semibold">{c.description}</p><p className="mt-1 text-xs text-ink-muted">{CATEGORY_LABELS[c.category]} · {new Date(c.expenseDate).toLocaleDateString("en-IN")}</p></div><div className="text-right"><p className="text-lg font-semibold">{money(c.amount)}</p><span className={`mt-1 inline-block rounded-full border px-2 py-1 text-[10px] ${statusClass(c.status)}`}>{STATUS_LABELS[c.status]}</span></div></div>{c.approvalNote?<p className="mt-3 rounded-lg bg-surface-2 p-2 text-xs text-ink-muted">Admin note: {c.approvalNote}</p>:null}<div className="mt-3 flex flex-wrap gap-2">{c.receiptOriginalName?<a href={`/api/expenses/${c._id}/receipt`} target="_blank" rel="noreferrer" className={ui.btnGhostSm}>View receipt</a>:<label className={`${ui.btnGhostSm} cursor-pointer`}>Upload receipt<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(c,f);e.currentTarget.value="";}}/></label>}{c.status==="pending"||c.status==="rejected"?<button className={ui.btnGhostSm} disabled={busy} onClick={()=>void deleteClaim(c)}>Delete</button>:null}</div></div>)}{!claims.length?<div className={`${ui.card} p-6 text-center text-sm text-ink-faint`}>No expense claims yet.</div>:null}</div></div>
  </div>;
}
