"use client";
import { useMemo, useState } from "react";
import { AuditLog } from "@/types/audit";

export function AuditLogClient({ initial }: { initial: AuditLog[] }) {
  const [logs,setLogs]=useState(initial); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const visible=useMemo(()=>{const q=search.trim().toLowerCase();return !q?logs:logs.filter(l=>[l.action,l.path,l.entityType,l.entityId,l.actor?.name,l.actor?.phone].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));},[logs,search]);
  const refresh=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/audit-logs?pageSize=100",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message||"Could not load logs");setLogs(j.data.logs);}catch(e){setError(e instanceof Error?e.message:"Could not load logs");}finally{setLoading(false);}};
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-accent">Security & accountability</p><h1 className="mt-1 text-3xl font-semibold">Audit Log</h1><p className="mt-2 text-sm text-ink-muted">Successful authenticated create/update/delete actions are captured centrally. Passwords, tokens and secrets are redacted.</p></div><button disabled={loading} onClick={()=>void refresh()} className="rounded-xl border border-border-default px-4 py-2 text-sm">{loading?"Refreshing…":"Refresh"}</button></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search action, actor, entity or route…" className="w-full rounded-xl border border-border-default bg-surface px-3 py-2.5 text-sm"/>{error&&<div className="rounded-xl border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error}</div>}{visible.length===0?<div className="rounded-2xl border border-dashed border-border-default p-10 text-center text-sm text-ink-muted">No audit events yet. New admin changes will appear here automatically.</div>:<div className="overflow-hidden rounded-2xl border border-border-default"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-2 text-xs uppercase tracking-wider text-ink-faint"><tr><th className="p-3">Time</th><th className="p-3">Actor</th><th className="p-3">Action</th><th className="p-3">Entity</th><th className="p-3">Result</th></tr></thead><tbody>{visible.map(l=><tr key={l._id} className="border-t border-border-default"><td className="whitespace-nowrap p-3 text-xs text-ink-muted">{new Date(l.createdAt).toLocaleString("en-IN")}</td><td className="p-3"><p className="font-medium">{l.actor?.name||"Admin"}</p><p className="text-xs text-ink-faint">{l.actor?.phone||l.actorRole}</p></td><td className="p-3"><p className="font-medium capitalize">{l.action}</p><p className="max-w-md truncate font-mono text-[10px] text-ink-faint">{l.method} {l.path}</p></td><td className="p-3"><p className="capitalize text-ink-muted">{l.entityType?.replace(/-/g," ")||"—"}</p><p className="font-mono text-[10px] text-ink-faint">{l.entityId||""}</p></td><td className="p-3"><span className="rounded-full border border-success/30 bg-success/10 px-2 py-1 text-xs text-success">{l.statusCode}</span></td></tr>)}</tbody></table></div></div>}</div>;
}
