"use client";
import { useMemo, useState } from "react";
import { ui } from "@/lib/ui-classes";
export interface CustomerSite { _id?:string; siteCode:string; label:string; address:string; city?:string; state?:string; countryCode:string; contactName?:string; contactPhone?:string; isPrimary:boolean; }
export interface CustomerMasterItem { _id:string; customerCode:string; name:string; phone:string; email?:string; customerType:"residential"|"commercial"|"enterprise"; status:"active"|"watch"|"inactive"; tags:string[]; taxId?:string; preferredLanguage:string; notes?:string; sites:CustomerSite[]; updatedAt:string; }
export function CustomerMasterClient({ initialCustomers, metrics }: { initialCustomers: CustomerMasterItem[]; metrics:{total:number;active:number;enterprise:number;multiSite:number} }) {
 const [rows,setRows]=useState(initialCustomers); const [search,setSearch]=useState(""); const [showCreate,setShowCreate]=useState(false); const [siteFor,setSiteFor]=useState<CustomerMasterItem|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return !q?rows:rows.filter(r=>[r.name,r.phone,r.email??"",r.customerCode,r.tags.join(" "),...r.sites.map(s=>s.address)].some(v=>v.toLowerCase().includes(q)));},[rows,search]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError(null);const f=new FormData(e.currentTarget);const body={name:String(f.get("name")||""),phone:String(f.get("phone")||""),email:String(f.get("email")||"")||undefined,customerType:String(f.get("customerType")||"residential"),tags:String(f.get("tags")||"").split(",").map(x=>x.trim()).filter(Boolean),site:{label:String(f.get("siteLabel")||"Primary site"),address:String(f.get("address")||""),city:String(f.get("city")||"")||undefined,state:String(f.get("state")||"")||undefined,countryCode:String(f.get("countryCode")||"IN")}};try{const r=await fetch("/api/customers-master",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Could not create customer");setRows(x=>[j.data.customer,...x]);setShowCreate(false);e.currentTarget.reset();}catch(err){setError(err instanceof Error?err.message:"Could not create customer");}finally{setBusy(false);}}
 async function addSite(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!siteFor)return;setBusy(true);setError(null);const f=new FormData(e.currentTarget);const body={label:String(f.get("label")||"Site"),address:String(f.get("address")||""),city:String(f.get("city")||"")||undefined,state:String(f.get("state")||"")||undefined,countryCode:String(f.get("countryCode")||"IN"),contactName:String(f.get("contactName")||"")||undefined,contactPhone:String(f.get("contactPhone")||"")||undefined,isPrimary:false};try{const r=await fetch(`/api/customers-master/${siteFor._id}/sites`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Could not add site");setRows(x=>x.map(v=>v._id===siteFor._id?j.data.customer:v));setSiteFor(null);}catch(err){setError(err instanceof Error?err.message:"Could not add site");}finally{setBusy(false);}}
 return <div className="space-y-5">
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Customers",metrics.total],["Active",metrics.active],["Enterprise",metrics.enterprise],["Multi-site",metrics.multiSite]].map(([l,v])=><div key={String(l)} className={`${ui.card} p-4`}><p className="text-[10px] uppercase tracking-wider text-ink-faint">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div>
  {error?<div className="rounded-xl border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error}</div>:null}
  <div className={`${ui.card} flex flex-col gap-3 p-4 sm:flex-row sm:items-center`}><input className={ui.input} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, phone, tag or site…"/><button className={ui.btnPrimary} onClick={()=>setShowCreate(v=>!v)}>+ Customer</button></div>
  {showCreate?<form onSubmit={create} className={`${ui.card} grid gap-3 p-4 md:grid-cols-2`}><input name="name" required className={ui.input} placeholder="Customer / company name"/><input name="phone" required className={ui.input} placeholder="Phone (+country code supported)"/><input name="email" type="email" className={ui.input} placeholder="Email"/><select name="customerType" className={ui.input}><option value="residential">Residential</option><option value="commercial">Commercial</option><option value="enterprise">Enterprise / multi-site</option></select><input name="tags" className={ui.input} placeholder="Tags: VIP, annual, high-value"/><input name="siteLabel" className={ui.input} defaultValue="Primary site"/><input name="address" required className={ui.input} placeholder="Primary site address"/><div className="grid grid-cols-3 gap-2"><input name="city" className={ui.input} placeholder="City"/><input name="state" className={ui.input} placeholder="State"/><input name="countryCode" className={ui.input} defaultValue="IN" maxLength={2}/></div><div className="md:col-span-2 flex justify-end gap-2"><button type="button" className={ui.btnGhost} onClick={()=>setShowCreate(false)}>Cancel</button><button disabled={busy} className={ui.btnPrimary}>{busy?"Saving…":"Create customer"}</button></div></form>:null}
  <div className="grid gap-4 xl:grid-cols-2">{filtered.map(c=><article key={c._id} className={`${ui.card} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-accent">{c.customerCode}</p><h2 className="mt-1 text-lg font-semibold">{c.name}</h2><p className="mt-1 text-sm text-ink-muted">{c.phone}{c.email?` · ${c.email}`:""}</p></div><span className="rounded-full border border-border-default px-2 py-1 text-[10px] uppercase text-ink-muted">{c.customerType}</span></div><div className="mt-3 flex flex-wrap gap-1.5">{c.tags.map(t=><span key={t} className="rounded-full bg-accent/10 px-2 py-1 text-[10px] text-accent">{t}</span>)}</div><div className="mt-4 space-y-2">{c.sites.map(s=><div key={s.siteCode} className="rounded-xl border border-border-default bg-surface-2 p-3"><div className="flex justify-between gap-3"><p className="text-sm font-semibold">{s.label}{s.isPrimary?" · Primary":""}</p><span className="font-mono text-[9px] text-ink-faint">{s.siteCode}</span></div><p className="mt-1 text-xs text-ink-muted">{s.address}{s.city?`, ${s.city}`:""}</p></div>)}</div><div className="mt-4 flex gap-2"><button className={ui.btnGhost} onClick={()=>setSiteFor(c)}>+ Site</button><a className={ui.btnGhost} href={`/dashboard/customers?q=${encodeURIComponent(c.phone)}`}>Customer 360</a></div></article>)}</div>
  {siteFor?<div className="fixed inset-0 z-[80] grid place-items-center pm-modal-backdrop p-4"><form onSubmit={addSite} className={`${ui.card} w-full max-w-lg space-y-3 p-5`}><div><p className="text-xs uppercase text-accent">Multi-site customer</p><h3 className="mt-1 text-lg font-semibold">Add site · {siteFor.name}</h3></div><input name="label" required className={ui.input} placeholder="Site label (Warehouse, HQ, Home…)"/><input name="address" required className={ui.input} placeholder="Address"/><div className="grid grid-cols-3 gap-2"><input name="city" className={ui.input} placeholder="City"/><input name="state" className={ui.input} placeholder="State"/><input name="countryCode" className={ui.input} defaultValue="IN" maxLength={2}/></div><div className="grid grid-cols-2 gap-2"><input name="contactName" className={ui.input} placeholder="Site contact"/><input name="contactPhone" className={ui.input} placeholder="Contact phone"/></div><div className="flex justify-end gap-2"><button type="button" className={ui.btnGhost} onClick={()=>setSiteFor(null)}>Cancel</button><button disabled={busy} className={ui.btnPrimary}>{busy?"Saving…":"Add site"}</button></div></form></div>:null}
 </div>;
}
