"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ui } from "@/lib/ui-classes";
import { TechnicianListItem } from "@/types/project";

type Severity = "critical"|"high"|"medium";
type Item = { id:string; kind:string; severity:Severity; title:string; detail:string; href:string; projectId?:string; customerName?:string; amount?:number; createdAt:string };
type Payload = { items:Item[]; metrics:{total:number;critical:number;high:number;unassigned:number;handover:number;reschedule:number} };
const tone:Record<Severity,string>={critical:"border-danger/35 bg-danger/10",high:"border-warning/35 bg-warning/10",medium:"border-border-default bg-surface"};

export function ExceptionInboxClient(){
  const[data,setData]=useState<Payload|null>(null); const[techs,setTechs]=useState<TechnicianListItem[]>([]); const[filter,setFilter]=useState("all"); const[busy,setBusy]=useState<string|null>(null); const[error,setError]=useState<string|null>(null);
  async function load(){setError(null);try{const[a,b]=await Promise.all([fetch("/api/operations/exceptions",{cache:"no-store"}),fetch("/api/technicians",{cache:"no-store"})]);const aj=await a.json();const bj=await b.json();if(!a.ok||!aj.success)throw new Error(aj.message||"Could not load exceptions");setData(aj.data);if(b.ok&&bj.success)setTechs(bj.data?.technicians??[]);}catch(e){setError(e instanceof Error?e.message:"Could not load exception inbox");}}
  useEffect(()=>{void load();},[]);
  const items=useMemo(()=>data?.items.filter(x=>filter==="all"||x.kind===filter)??[],[data,filter]);
  async function handover(item:Item,technicianId:string){if(!item.projectId||!technicianId)return;setBusy(item.id);setError(null);try{const r=await fetch(`/api/projects/${item.projectId}/reassign`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({technicianId,reason:`Exception Inbox handover: ${item.title}`})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Handover failed");await load();}catch(e){setError(e instanceof Error?e.message:"Handover failed");}finally{setBusy(null);}}
  if(!data&&!error)return <div className={`${ui.card} p-8 text-sm text-ink-muted`}>Building today’s exception inbox…</div>;
  return <div className="space-y-5">
    {error?<div className="rounded-xl border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{error}</div>:null}
    {data?<div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{[["Needs action",data.metrics.total],["Critical",data.metrics.critical],["High",data.metrics.high],["Unassigned",data.metrics.unassigned],["Handover",data.metrics.handover],["Reschedule",data.metrics.reschedule]].map(([l,v])=><div key={String(l)} className={`${ui.card} p-4`}><p className="text-[10px] font-semibold uppercase tracking-wider text-ink-faint">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div>:null}
    <div className="flex flex-wrap gap-2">{[["all","All"],["unassigned","Unassigned"],["off_duty_assignment","Off-duty"],["failed_visit","Failed visits"],["reschedule","Reschedules"],["overdue_job","Overdue jobs"],["overdue_invoice","Payments"],["sla_complaint","SLA"]].map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={`rounded-full border px-3 py-1.5 text-xs ${filter===k?"border-accent bg-accent/10 text-accent":"border-border-default text-ink-muted"}`}>{l}</button>)}</div>
    <div className="space-y-3">{items.length?items.map(item=><article key={item.id} className={`rounded-2xl border p-4 ${tone[item.severity]}`}><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${item.severity==="critical"?"bg-danger/15 text-danger":item.severity==="high"?"bg-warning/15 text-warning":"bg-surface-2 text-ink-muted"}`}>{item.severity}</span><span className="text-[10px] uppercase tracking-wider text-ink-faint">{item.kind.replaceAll("_"," ")}</span></div><h3 className="mt-2 font-semibold">{item.title}</h3><p className="mt-1 text-sm text-ink-muted">{item.detail}</p></div><div className="flex flex-wrap items-center gap-2">{item.projectId&&(item.kind==="off_duty_assignment"||item.kind==="failed_visit")?<select disabled={busy===item.id} defaultValue="" onChange={e=>{if(e.target.value)void handover(item,e.target.value)}} className="h-9 rounded-lg border border-border-default bg-surface px-2 text-xs"><option value="">Handover to…</option>{techs.filter(t=>t.isActive&&t.dutyStatus!=="off_duty").map(t=><option key={t.id} value={t.id}>{t.name} • {t.dutyStatus.replaceAll("_"," ")}</option>)}</select>:null}<Link href={item.href} className={ui.btnGhost}>Fix now →</Link></div></div></article>):<div className={`${ui.card} p-10 text-center`}><p className="text-lg font-semibold text-success">✓ No chaos here</p><p className="mt-2 text-sm text-ink-muted">No exceptions match this view.</p></div>}</div>
  </div>;
}
