"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Project, SERVICE_TYPE_LABELS, ProjectStatus } from "@/types/project";
import { Quotation } from "@/types/quotation";
import { ui } from "@/lib/ui-classes";

type Item = { description: string; quantity: number; rate: number };
const todayPlus = (days: number) => { const d = new Date(); d.setDate(d.getDate() + days); return d.toISOString().slice(0, 10); };

export default function InvoiceForm({ projects, quotations }: { projects: Project[]; quotations: Quotation[] }) {
  const router = useRouter();
  const eligible = projects.filter(p => p.status !== ProjectStatus.CANCELLED);
  const [projectId, setProjectId] = useState(eligible[0]?._id ?? "");
  const [dueDate, setDueDate] = useState(todayPlus(7));
  const [items, setItems] = useState<Item[]>([{ description: "Pest control service", quantity: 1, rate: 0 }]);
  const [discount, setDiscount] = useState(0); const [taxRate, setTaxRate] = useState(18); const [additionalCharges, setAdditionalCharges] = useState(0);
  const [terms, setTerms] = useState("Payment is due by the due date shown on this invoice. Service warranty and revisit terms are subject to the approved quotation/service agreement.");
  const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const selected = eligible.find(p => p._id === projectId);
  const linkedQuote = quotations.find(q => q.convertedProjectId === projectId);
  const subtotal = items.reduce((s, x) => s + x.quantity * x.rate, 0); const taxable = Math.max(0, subtotal - discount); const tax = taxable * taxRate / 100; const total = taxable + tax + additionalCharges;
  const money = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(n || 0);
  const canUseQuote = Boolean(linkedQuote);

  function useQuotation() { if (!linkedQuote) return; setItems(linkedQuote.items.map(i => ({ description: i.description, quantity: i.quantity, rate: i.rate }))); setDiscount(linkedQuote.discount); setTaxRate(linkedQuote.taxRate); setAdditionalCharges(linkedQuote.additionalCharges); setTerms(linkedQuote.terms || terms); }
  function updateItem(index: number, patch: Partial<Item>) { setItems(v => v.map((x, i) => i === index ? { ...x, ...patch } : x)); }
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); if (!projectId) return setError("Select a project"); if (items.some(x => !x.description.trim() || x.quantity <= 0 || x.rate < 0)) return setError("Complete all invoice line items"); setBusy(true); try { const res = await fetch("/api/invoices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, dueDate, items, discount, taxRate, additionalCharges, notes, terms }) }); const json = await res.json(); if (!res.ok || !json.success) throw new Error(json.message || "Invoice creation failed"); router.push(`/dashboard/invoices/${json.data.invoice._id}`); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Invoice creation failed"); setBusy(false); } }

  return <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[1fr_360px]">
    <div className="space-y-5">
      <section className={`${ui.card} p-6`}><p className="text-xs uppercase tracking-[.16em] text-ink-faint">Bill against project</p><div className="mt-4 grid gap-4 md:grid-cols-2"><label><span className={ui.label}>Project</span><select className={`${ui.input} mt-1.5`} value={projectId} onChange={e => setProjectId(e.target.value)}>{eligible.map(p => <option value={p._id} key={p._id}>{p.projectCode} · {p.customerName} · {SERVICE_TYPE_LABELS[p.serviceType]}</option>)}</select></label><label><span className={ui.label}>Payment due date</span><input type="date" className={`${ui.input} mt-1.5`} value={dueDate} onChange={e => setDueDate(e.target.value)} /></label></div>{selected && <div className="mt-4 rounded-xl bg-surface-2 p-4 text-sm"><b>{selected.customerName}</b><p className="mt-1 text-ink-muted">{selected.customerPhone} · {selected.address}</p></div>}{canUseQuote && <button type="button" onClick={useQuotation} className={`${ui.btnGhostSm} mt-4`}>Use accepted quotation pricing</button>}</section>
      <section className={`${ui.card} p-6`}><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-ink-faint">Line items</p><h2 className="mt-1 text-xl font-semibold">Services & charges</h2></div><button type="button" className={ui.btnGhostSm} onClick={() => setItems(v => [...v, { description: "", quantity: 1, rate: 0 }])}>+ Add item</button></div><div className="mt-5 space-y-3">{items.map((item, index) => <div className="grid gap-3 rounded-xl border border-border-default bg-surface-2 p-4 md:grid-cols-[1fr_110px_150px_120px_auto]" key={index}><input className={ui.input} placeholder="Service description" value={item.description} onChange={e => updateItem(index, { description: e.target.value })} /><input className={ui.input} type="number" min="0.01" step="0.01" value={item.quantity} onChange={e => updateItem(index, { quantity: Number(e.target.value) })} /><input className={ui.input} type="number" min="0" step="0.01" value={item.rate} onChange={e => updateItem(index, { rate: Number(e.target.value) })} /><div className="flex items-center justify-end font-medium">{money(item.quantity * item.rate)}</div><button aria-label="Remove item" type="button" className="text-danger disabled:opacity-40" disabled={items.length === 1} onClick={() => setItems(v => v.filter((_, i) => i !== index))}>×</button></div>)}</div></section>
      <section className={`${ui.card} p-6`}><div className="grid gap-4 md:grid-cols-2"><label><span className={ui.label}>Terms</span><textarea className={`${ui.input} mt-1.5 min-h-28 py-3`} value={terms} onChange={e => setTerms(e.target.value)} /></label><label><span className={ui.label}>Internal notes</span><textarea className={`${ui.input} mt-1.5 min-h-28 py-3`} value={notes} onChange={e => setNotes(e.target.value)} /></label></div></section>
    </div>
    <aside className="space-y-4"><div className={`${ui.card} sticky top-5 p-6`}><p className="text-xs uppercase tracking-[.16em] text-ink-faint">Invoice summary</p><div className="mt-5 space-y-3"><label><span className={ui.label}>Discount (₹)</span><input className={`${ui.input} mt-1.5`} type="number" min="0" value={discount} onChange={e => setDiscount(Number(e.target.value))} /></label><label><span className={ui.label}>GST / Tax (%)</span><input className={`${ui.input} mt-1.5`} type="number" min="0" max="100" value={taxRate} onChange={e => setTaxRate(Number(e.target.value))} /></label><label><span className={ui.label}>Additional charges (₹)</span><input className={`${ui.input} mt-1.5`} type="number" min="0" value={additionalCharges} onChange={e => setAdditionalCharges(Number(e.target.value))} /></label></div><div className="mt-6 space-y-2 border-t border-border-default pt-5 text-sm"><div className="flex justify-between"><span className="text-ink-muted">Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between"><span className="text-ink-muted">Discount</span><span>- {money(discount)}</span></div><div className="flex justify-between"><span className="text-ink-muted">Tax</span><span>{money(tax)}</span></div><div className="flex justify-between"><span className="text-ink-muted">Additional</span><span>{money(additionalCharges)}</span></div><div className="flex justify-between border-t border-border-default pt-3 text-xl font-semibold"><span>Total</span><span className="text-accent">{money(total)}</span></div></div>{error && <p className={`${ui.errorText} mt-4`}>{error}</p>}<button disabled={busy || !eligible.length} className={`${ui.btnPrimary} mt-6 w-full`}>{busy ? "Creating…" : "Create draft invoice"}</button>{!eligible.length && <p className="mt-3 text-xs text-warning">Create a project before generating an invoice.</p>}</div></aside>
  </form>;
}
