import { Document, Schema, Types, model } from "mongoose";
export enum ApprovalStatus { PENDING = "pending", APPROVED = "approved", REJECTED = "rejected" }
export enum ApprovalCategory { EXPENSE = "expense", DISCOUNT = "discount", REFUND = "refund", STOCK = "stock_adjustment", PURCHASE = "purchase", OTHER = "other" }
export interface IApprovalRequest extends Document { _id: Types.ObjectId; companyId?: Types.ObjectId; branchId?: Types.ObjectId; approvalNumber: string; category: ApprovalCategory; title: string; description?: string; amount?: number; relatedType?: string; relatedId?: Types.ObjectId; status: ApprovalStatus; requestedBy: Types.ObjectId; requestedByName?: string; resolvedBy?: Types.ObjectId; resolutionNote?: string; resolvedAt?: Date; createdAt: Date; updatedAt: Date; }
const schema = new Schema<IApprovalRequest>({
  companyId: { type: Schema.Types.ObjectId, ref: "Company", index: true }, branchId: { type: Schema.Types.ObjectId, ref: "Branch", index: true }, approvalNumber: { type: String, required: true, index: true }, category: { type: String, enum: Object.values(ApprovalCategory), required: true, index: true }, title: { type: String, required: true, trim: true, maxlength: 180 }, description: { type: String, trim: true, maxlength: 2000 }, amount: { type: Number, min: 0 }, relatedType: { type: String, trim: true, maxlength: 80 }, relatedId: { type: Schema.Types.ObjectId }, status: { type: String, enum: Object.values(ApprovalStatus), default: ApprovalStatus.PENDING, index: true }, requestedBy: { type: Schema.Types.ObjectId, ref: "User", required: true }, requestedByName: { type: String, trim: true, maxlength: 120 }, resolvedBy: { type: Schema.Types.ObjectId, ref: "User" }, resolutionNote: { type: String, trim: true, maxlength: 1000 }, resolvedAt: { type: Date },
}, { timestamps: true });
schema.index({ companyId: 1, branchId: 1, status: 1, createdAt: -1 });
export const ApprovalRequest = model<IApprovalRequest>("ApprovalRequest", schema);
